version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Powersmart123!
      MYSQL_DATABASE: power_smart_site
    ports:
      - "3306:3306"
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: Powersmart123!
      DOCKER_INFLUXDB_INIT_ORG: powersmart
      DOCKER_INFLUXDB_INIT_BUCKET: sensor_data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: powersmart
      MINIO_ROOT_PASSWORD: Powersmart123!
    command: server /data --console-address ":9001"

  nacos:
    image: nacos/nacos-server:2.2.3
    ports:
      - "8848:8848"
    environment:
      MODE: standalone

volumes:
  mysql-data:
