server:
  port: 8083

spring:
  application:
    name: power-smart-progress
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/power_smart_site?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.powersmart.progress: debug
